name: Run tests
on: [push, pull_request]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          token: ${{ github.token }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Check whether snapshot builds
        run: npm run snapshots

      - name: Check whether locales build
        run: npm run locales

      - name: Check whether the code builds
        run: npm run build
